version: '3.1'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: entreprise
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
